### PR TITLE
Implement authentication.

### PR DESCRIPTION
**Pull request by christopherjmedlin**

### CODE REVIEW

**Comment by christopherjmedlin** [comment]
[Implement JWT authorization](https://trello.com/c/NOv6md3u/11-implement-jwt-authorization)

**Comment by christopherjmedlin** [comment]
[Implement user and authentication API](https://trello.com/c/jg5Ovfy0/9-implement-user-and-authentication-api)

**Review by AleksVidmantas — APPROVED** [review]
Looks good.

**Review by IvanKenevich — APPROVED** [review]
Create a constant for token expiry time instead of hardcoding

**Pull request merged**
